spring:
  profiles:
    active:
    - dev
---
server: 
  port: 8201 
spring:
  profiles: dev
  application: 
    name: microservice-config-client
eureka: 
  client: 
    service-url: 
      defaultZone: http://119.23.253.49//eureka
---
server: 
  port: 8202 
spring:
  profiles: test
  application: 
    name: microservice-config-client
eureka: 
  client: 
    service-url: 
      defaultZone: http://119.23.253.49//eureka
 

